export interface BossBiography {
  bossId: string;
  title: string;
  abilityExplanation: string;
  biography: string;
}

/** These entries are intended to unlock as readable lore after boss victories. */
export const BOSS_BIOGRAPHIES: BossBiography[] = [
  {
    bossId: "boss.aether-sovereign",
    title: "Aether Sovereign: The Racer Who Learned to Listen Upward",
    abilityExplanation: "Aether Sovereign's unusual control comes from years of reading pressure changes through his body and equipment. The Sky Dominion trained him around open air, suspended track, and wind shear, while a rare aether-thread frame lets him convert small pressure differences into steering corrections. The knights beneath him use standard flight rigs; he has a tuned instrument built from a route that no longer exists.",
    biography: "Before anyone called him Sovereign, he was simply Aeri, a courier who hated stairs and loved impossible shortcuts. He grew up on the lower shelves of the Sky Dominion, where the safest paths were marked in white and the dangerous paths were marked in red. Aeri preferred the paths marked with a question mark. His first race was not planned. A tournament racer lost a wheel brace, Aeri borrowed it, and a gust carried him across a gap that had been considered too wide for any sensible orb. The crowd thought it was skill. Aeri knew it was luck. He landed upside down, bounced off a weather vane, and crossed the finish line backward while apologizing to the judge. The official record called it an innovative aerial recovery. The judge privately called it a paperwork emergency. Either way, Aeri was invited back. His early races were embarrassing collections of wind-tossed failures, so he studied every one. He learned that air was not empty space between obstacles; it had rhythm, temperature, pressure, and memory. He began racing with his eyes closed for short stretches, feeling currents through vibration. Older racers laughed until he predicted gusts before their instruments did. The turning point came during the collapse of the Upper Ribbon, a suspended route that broke into seven drifting pieces. Aeri could have escaped with the other racers. Instead, he kept returning to guide stranded competitors across the fragments. He reached the final platform with a cracked frame and no recorded finishing time. The Dominion awarded him the title of Sovereign because the people he saved started using it first. His abilities are therefore part science, part equipment, and part habit formed under pressure. The knights of the Sky Dominion are skilled pilots, but they are trained to obey stable signals and approved routes. Aether Sovereign learned to decide when the signals disagreed. His advantage is not a magical inheritance. It is the result of corrections, a rare frame, and one lucky accident that taught him never to ignore the wind. He still dislikes being treated as a legend. When asked how he rose so high, he says, 'A wheel fell off, the weather panicked, and everyone made a generous administrative decision.' Then he offers a rematch.",
  },
  {
    bossId: "boss.cinder-axis",
    title: "Cinder Axis: The Patient Weight of Preparation",
    abilityExplanation: "Cinder Axis can cross heat channels and redirect force because his body and equipment were gradually adapted to volcanic terrain. His heat-resistant shell is layered with cooled volcanic glass, and his route discipline lets him conserve momentum where ordinary racers lose control. Ash Banner knights have protective gear, but Cinder Axis personally rebuilt his around repeated failures in live terrain.",
    biography: "Cinder Axis began as a name on a maintenance list. The list belonged to a training yard in the Ash Banner, where young racers practiced crossing warm stone without cracking their shells. He was not the fastest trainee, not the loudest, and not the one instructors expected to lead. He was the one who arrived early to inspect the route and stayed late to repair pieces everyone else had broken. His rise was built on work that looked unimportant from a distance. He tested temperatures, recorded cooling times, and learned which volcanic glass failed under sudden impact. When other racers celebrated a difficult victory, Cinder Axis asked what had nearly gone wrong. Some found this irritating. A few found it useful. The useful few kept returning to train with him. His first major victory was almost cancelled by a stone bridge that overheated beneath the starting line. Officials wanted to postpone the race. Cinder Axis argued that the route was dangerous but readable if everyone received a proper warning. He spent the delay helping other racers adjust their equipment. When the race began, he did not dominate. He made fewer mistakes than everyone else. By the final bend, the racers he had helped were still moving, while the favourites had overheated or lost traction. The Ash Banner did not see a lucky champion; they saw someone who had made preparation communal. He became a route captain, then keeper of the heat gates, and finally the figure trusted whenever the terrain behaved badly. His title refers to the line he draws between danger and usefulness: a hot route should not be feared blindly, but neither should it be treated casually. His unique abilities come from the same philosophy. The knights beneath him receive excellent protection and train on controlled courses. Cinder Axis trained on damaged courses, rebuilt his shell after every failure, and learned to shift weight before the surface visibly changed. His gear is not simply stronger; it is tuned to respond to heat gradients and uneven cooling. His apparent power is thousands of deliberate preparations becoming instinct. He remains protective of inexperienced racers, though he hides it behind criticism. If he says someone’s equipment is foolish, he may already have prepared a safer replacement. If he asks whether they studied the route, he is usually hoping they will say no so he can teach them himself.",
  },
  {
    bossId: "boss.glacier-sigil",
    title: "Glacier Sigil: The Keeper of Paths That Melted",
    abilityExplanation: "Glacier Sigil's abilities come from memory, surface reading, and an old frost-sigil system embedded in her equipment. The system responds to tiny changes in temperature and traction, allowing her to prepare for ice shifts before they become visible. Frost Reign knights use the same principles in simplified form; Glacier Sigil carries an original route-marking core from an older generation of tracks.",
    biography: "Glacier Sigil did not set out to become a boss. She wanted to preserve a road. In the Frost Reign, roads are temporary in a way outsiders rarely understand. A track can freeze into existence, serve racers for a season, and disappear beneath a new layer of ice. Her first work was marking those changes so repair crews and travellers would not mistake an old path for a safe one. She was young when she began, and her marks were considered too plain. Other cartographers preferred ornate symbols that looked beautiful in snow. Glacier Sigil used short lines, small circles, and practical warnings. Her maps were not admired until a thaw erased decorative maps and left her useful marks visible beneath the meltwater. Her first promotion came during a quiet disaster. A training route shifted overnight, opening a smooth-looking shelf above a deep fracture. She noticed that the ice reflected starlight differently along one edge. She delayed the morning race, walked the route herself, and discovered the hollow beneath it. The delay annoyed officials, but it prevented a collapse. Afterward, the same officials asked her to inspect every major route. She rose slowly because she refused shortcuts. She remembered the names of fallen markers, the sound of safe ice, and the habits of racers who ignored warnings. When older route-keepers retired, there was no dramatic vote. People simply began bringing their maps to Glacier Sigil first. Her authority formed through trust repeated so many times that it became tradition. Her distinctive power is not merely cold resistance. She can read the small conversation between a surface and the weight moving across it. The frost-sigil core in her equipment was recovered from a route built before the current Frost Reign. It translates pressure, temperature, and vibration into patterns she has spent years learning. A knight can follow the pattern. Glacier Sigil can understand what it is about to become. That difference explains why her knights are capable but less extraordinary. They are trained to protect the route and obey marked signals. She learned when a mark was outdated, when a safe line was becoming unsafe, and when the best path was to stop. Her greatest ability is patience sharp enough to look like foresight. After defeat, she does not call the route conquered. She says it has been remembered by one more person, which, in the Frost Reign, is a form of victory.",
  },
  {
    bossId: "boss.rift-echelon",
    title: "Rift Echelon: The Champion Who Was in the Wrong Place",
    abilityExplanation: "Rift Echelon's abilities come from repeated exposure to unstable routes and a rare veil-thread body modification that allows brief phase-like shifts in position. The effect is limited, tiring, and unreliable outside rift conditions. Null Veil knights use controlled versions for signalling and scouting; Rift Echelon learned to race through dangerous edge cases where the system misbehaves.",
    biography: "Rift Echelon’s official biography begins with three different dates, two contradictory birthplaces, and a note saying ‘please stop editing this form.’ Their own version is shorter: they took a wrong turn and kept winning. They worked as a route runner in the Null Veil, carrying messages between places that did not always remain adjacent. The job required speed, but mostly it required remembering which door led somewhere today. Rift Echelon was good at the work because they treated mistakes as information. If a corridor moved, they made a note. If a bridge appeared twice, they gave it two names. If a finish line sent them to a laundry room, they delivered the message and apologized to the laundry. During an informal race, they followed a route marker that had been placed upside down. Instead of reaching the expected circuit, they entered a narrow rift and emerged halfway through the final lap of a much larger competition. Officials tried to remove them. The crowd began cheering. A rival challenged them to finish the lap. Rift Echelon did, despite having no idea which race they were in, and won by taking a shortcut through a gap that was open only because reality had not finished deciding where the wall belonged. That victory should have been a curiosity. Instead, it became a pattern. Rift Echelon began entering races with incomplete information, testing seams that other racers avoided. Some attempts ended in humiliating returns to the starting line. One ended with their equipment stuck in a sign. Another ended with them winning a trophy engraved for a person who had not yet been born. Through it all, they learned how to remain calm when the track stopped agreeing with itself. Their rise was not carefully planned, although they later claimed it was. The Null Veil followed them because they made uncertainty feel survivable. Their knights are trained in veil technique, but most are taught to use it under approved conditions. Rift Echelon learned from accidents, loopholes, and badly maintained boundaries. Their rare body modification can briefly align with a rift, producing movements that look impossible but carry real physical costs. They do not consider themselves a liar. They consider truth a route with too many entrances. After defeat, they may provide a sincere explanation, a misleading explanation, and a completely ridiculous explanation. The irritating part is that all three may contain a piece of the truth.",
  },
  {
    bossId: "boss.circuit-steward",
    title: "The Circuit Steward: The Boss Who Inherited a Queue",
    abilityExplanation: "The Circuit Steward's abilities are coordination-based rather than purely physical. Their interface can synchronize checkpoints, relay route timing, and briefly redirect compatible track systems. It is a creator-era coordination device that was meant for maintenance crews, not combat. The Steward became exceptional by learning to use it under overlapping stage conditions; League knights operate the safer, narrower version.",
    biography: "The Circuit Steward rose to power because nobody else wanted the job. That is not an insult. It is the official explanation, the unofficial explanation, and the explanation the Steward gives while handing someone a form. Before the title, they were a checkpoint clerk in the Convergence League. Their station was small, badly lit, and located where three routes overlapped. Racers arrived from different regions, carrying different rules, different time readings, and occasionally pieces of track that had not existed when they left. The previous clerk resigned after a sign instructed them to report to themselves. The replacement lasted six minutes. The Steward stayed because someone had to return the stamps to the drawer. At first, the work was ordinary. They checked entries, corrected names, and explained that ‘the race ended yesterday’ was not a valid reason to skip registration. Then the route network began to fail. Checkpoints opened in the wrong order. Finish lines appeared before starts. Teams were sent to stages retired years earlier. The Steward discovered that an old coordination console still worked if every route was entered in the correct sequence. The problem was that nobody knew the correct sequence. The Steward solved it by observing people. They recorded which racers arrived together, which routes changed after weather events, and which signs were most likely to be lying. They did not calculate the entire network. They built enough trust in the records to make the network usable. When the League needed someone to coordinate an emergency multi-route race, the Steward was the only person who knew where everyone was supposed to be, even if several places were currently theoretical. Their rise was part persistence, part bureaucracy, and part collective exhaustion. Racers followed because the Steward could turn confusion into a schedule. The schedule was often wrong, but it was wrong in a way that could be corrected. The unique abilities come from the creator-era console linked to their equipment. It can synchronize compatible route systems, redirect checkpoint signals, and expose hidden timing conflicts. League knights can use standard relay tools, but they are trained for one station at a time. The Steward learned to manage many overlapping states while moving through the network personally. They do not claim to be the strongest racer. They claim strength is less useful when everyone else is lost. After defeat, the Steward offers the player a victory stamp, a revised schedule, and an apology for the schedule being revised while they were reading it.",
  },
];

export const getBossBiography = (bossId: string): BossBiography | undefined =>
  BOSS_BIOGRAPHIES.find((biography) => biography.bossId === bossId);
