import type { CharacterRecord } from "./characterDatabase";

export const CHARACTER_DATABASE_BATCH_03: CharacterRecord[] = [
  {
    id: "npc.marble-archivist", name: "The Marble Archivist", importance: "major", function: "guide", origin: "A sealed archive beneath an abandoned creator-era race hall.", personality: ["patient", "precise", "secretly theatrical"], traits: ["preserves old records", "compares contradictory diagrams", "speaks to empty shelves"], strengths: ["historical memory", "analysis", "organisation"], weaknesses: ["protects incomplete records too fiercely", "mistakes age for authority"], storyUse: "Connects the current racing worlds to ordinary creators without revealing the entire mystery at once.", firstContact: "Asks the player to return a record that the player has never seen.", recurrence: "campaign", loreWeight: "heavy",
  },
  {
    id: "npc.sunken-scribe", name: "Sunken Scribe", importance: "supporting", function: "world-worker", origin: "A writing station beneath a route that floods whenever a finish line activates.", personality: ["quiet", "diligent", "dryly hopeful"], traits: ["copies wet records", "uses waterproof ink", "keeps writing during alarms"], strengths: ["persistence", "record keeping", "calm"], weaknesses: ["ignores personal danger", "refuses to discard damaged evidence"], storyUse: "Adds a grounded witness to dimensional transitions and preserves clues that would otherwise disappear.", firstContact: "Offers a page that is still dripping but somehow legible.", recurrence: "occasional", loreWeight: "heavy",
  },
  {
    id: "npc.choir-of-static", name: "Choir of Static", importance: "recurring", function: "event-contact", origin: "A group of signal fragments that began answering one another across broken checkpoints.", personality: ["collective", "curious", "easily distracted"], traits: ["repeats player actions", "harmonizes warnings", "loses members during interference"], strengths: ["communication", "pattern recognition", "coverage"], weaknesses: ["contradictory voices", "forgets which warning came first"], storyUse: "Makes Static's unknown origin less isolated and introduces the possibility of distributed intelligence.", firstContact: "Several voices greet the player using the same name at different times.", recurrence: "recurring", loreWeight: "heavy",
  },
  {
    id: "npc.undertow-porter", name: "Undertow Porter", importance: "supporting", function: "world-worker", origin: "A low route where equipment and racers are carried between elevation bands.", personality: ["practical", "strong-willed", "friendly when rested"], traits: ["moves heavy parts", "knows hidden lifts", "charges fair rates"], strengths: ["strength", "logistics", "local knowledge"], weaknesses: ["refuses shortcuts", "complains about unnecessary weight"], storyUse: "Makes material movement and upgrade logistics feel like part of the world.", firstContact: "Asks whether the player really needs to carry every mysterious object at once.", recurrence: "occasional", loreWeight: "light",
  },
  {
    id: "npc.lantern-may", name: "Lantern May", importance: "recurring", function: "friend", origin: "A route-lit settlement where lanterns are placed to mark paths that survived the night.", personality: ["warm", "brave", "superstitious in practical ways"], traits: ["maintains route lights", "knows night hazards", "welcomes lost racers"], strengths: ["care", "navigation", "community"], weaknesses: ["trusts old omens", "stays too long in dangerous places"], storyUse: "Adds a softer social perspective on routes, danger, and what it means for a track to remain open.", firstContact: "Offers a lantern and insists that it is only slightly haunted.", recurrence: "recurring", loreWeight: "moderate",
  },
  {
    id: "npc.rivet-king", name: "Rivet King", importance: "supporting", function: "world-worker", origin: "A repair yard where structural parts are sorted by sound instead of labels.", personality: ["boisterous", "generous", "competitive"], traits: ["tests metal by tapping", "names every machine", "hosts repair contests"], strengths: ["craft", "material judgment", "morale"], weaknesses: ["overbuilds everything", "cannot whisper near machinery"], storyUse: "Adds comic engineering culture and provides a second repair personality distinct from Quarry and Needle Nell.", firstContact: "Challenges the player to identify a safe part by its sound.", recurrence: "occasional", loreWeight: "light",
  },
  {
    id: "npc.pebble-prince", name: "Pebble Prince", importance: "background", function: "acquaintance", origin: "A tiny stone settlement that crowns whoever finds the smallest useful rock.", personality: ["proud", "polite", "dramatic"], traits: ["collects pebbles", "announces local rules", "takes tiny victories seriously"], strengths: ["confidence", "social memory", "enthusiasm"], weaknesses: ["overstates importance", "cannot resist a ceremony"], storyUse: "Keeps the world playful and prevents every strange location from feeling ominous.", firstContact: "Offers a ceremonial pebble that is immediately misplaced.", recurrence: "occasional", loreWeight: "light",
  },
  {
    id: "npc.faraday-finch", name: "Faraday Finch", importance: "supporting", function: "world-worker", origin: "A magnetic ridge used to study how metal objects respond to changing routes.", faction: "Amber Circuit", personality: ["curious", "methodical", "easily excited"], traits: ["maps magnetic fields", "tests equipment", "writes overly long notes"], strengths: ["science", "measurement", "experimentation"], weaknesses: ["forgets social timing", "tests ideas before explaining them"], storyUse: "Expands the material and physics side of the setting through an approachable researcher.", firstContact: "Asks the player to hold still while the ridge attempts to rearrange their equipment.", recurrence: "recurring", loreWeight: "moderate",
  },
  {
    id: "npc.mirror-mara", name: "Mirror Mara", importance: "recurring", function: "acquaintance", origin: "A reflective cave that shows routes from slightly different attempts.", personality: ["observant", "playful", "emotionally guarded"], traits: ["compares reflections", "recognizes failed approaches", "avoids direct predictions"], strengths: ["comparison", "empathy", "pattern reading"], weaknesses: ["dwells on alternatives", "sometimes follows a reflection"], storyUse: "Explores possibility and failed routes without making alternate timelines literal canon.", firstContact: "Asks whether the player wants advice from the version that nearly won.", recurrence: "recurring", loreWeight: "heavy",
  },
  {
    id: "npc.salt-analog", name: "Salt Analog", importance: "supporting", function: "event-contact", origin: "A dry basin where old route measurements are preserved in salt layers.", personality: ["literal", "patient", "surprisingly sarcastic"], traits: ["reads mineral layers", "compares old temperatures", "corrects exaggerated histories"], strengths: ["geology", "memory", "accuracy"], weaknesses: ["rejects useful intuition", "takes sarcasm literally"], storyUse: "Connects environmental science to the creator mystery through physical evidence.", firstContact: "Corrects the age of a track before saying hello.", recurrence: "occasional", loreWeight: "moderate",
  },
  {
    id: "npc.rail-bell", name: "Rail Bell", importance: "background", function: "world-worker", origin: "A route alarm that developed a personality after being struck by too many racers.", personality: ["loud", "helpful", "easily offended"], traits: ["announces hazards", "remembers collisions", "rings at bad jokes"], strengths: ["warning", "timing", "reliability"], weaknesses: ["overreacts to harmless contact", "cannot lower its volume"], storyUse: "Turns environmental warnings into a memorable object-character with comic timing.", firstContact: "Rings before the player reaches the obstacle and then rings again for emphasis.", recurrence: "occasional", loreWeight: "light",
  },
  {
    id: "npc.nettle-judge", name: "Nettle Judge", importance: "major", function: "event-contact", origin: "An independent challenge court that evaluates whether races were fair rather than merely won.", personality: ["strict", "fair", "secretly sentimental"], traits: ["reviews route conditions", "rejects dishonest shortcuts", "remembers sportsmanship"], strengths: ["judgment", "fairness", "observation"], weaknesses: ["overformalises fun", "struggles with dimensional exceptions"], storyUse: "Provides a neutral perspective on challenge fairness and helps prevent arbitrary victory conditions.", firstContact: "Requests a report on whether the finish line behaved fairly.", recurrence: "recurring", loreWeight: "moderate",
  },
  {
    id: "npc.ghost-lap", name: "Ghost Lap", importance: "supporting", function: "acquaintance", origin: "A recorded race attempt that keeps replaying after its racer disappeared.", personality: ["focused", "polite", "unaware of the problem"], traits: ["repeats one route", "greets observers", "cannot finish the final turn"], strengths: ["consistency", "memory", "route knowledge"], weaknesses: ["cannot adapt", "does not know it is incomplete"], storyUse: "Offers a gentle, unresolved mystery connected to unfinished routes and creator-era records.", firstContact: "Thanks the player for watching a race that has been over for years.", recurrence: "occasional", loreWeight: "heavy",
  },
  {
    id: "npc.vaultkeeper-io", name: "Vaultkeeper Io", importance: "major", function: "guide", origin: "A sealed material vault that opens only when its inventory and its memory agree.", personality: ["reserved", "helpful", "cautiously curious"], traits: ["protects rare parts", "checks provenance", "asks difficult questions"], strengths: ["security", "history", "resource judgment"], weaknesses: ["hoards information", "assumes every object has a hidden cost"], storyUse: "Controls access to rare upgrade materials and creator-era components without turning rewards into arbitrary locks.", firstContact: "Asks what the player intends to repair before offering anything valuable.", recurrence: "recurring", loreWeight: "heavy",
  },
  {
    id: "rival.quartz-quick", name: "Quartz Quick", importance: "recurring", function: "rival", origin: "A crystal-course circuit where route readability matters more than raw speed.", faction: "Amber Circuit", personality: ["bright", "competitive", "impatient"], traits: ["spots reflective lines", "changes tactics quickly", "celebrates close finishes"], strengths: ["reaction", "route reading", "adaptation"], weaknesses: ["rushes explanations", "takes quiet rivals lightly"], storyUse: "Adds a high-energy rival who challenges visual and environmental reading.", firstContact: "Claims the best route is the one that shines, then discovers not every shine is helpful.", recurrence: "recurring", loreWeight: "light",
  },
  {
    id: "rival.ashen-foil", name: "Ashen Foil", importance: "supporting", function: "rival", origin: "A heat-route fencing club where racers practise controlled deflections.", faction: "Ash Banner", personality: ["polished", "competitive", "dramatic"], traits: ["uses elegant deflections", "studies opponents", "keeps theatrical scorecards"], strengths: ["control", "timing", "presentation"], weaknesses: ["overvalues style", "dislikes messy victories"], storyUse: "Adds a stylish rival who treats racing as performance without becoming cruel or villainous.", firstContact: "Challenges the player to win beautifully, then accepts an ugly victory if it is honest.", recurrence: "occasional", loreWeight: "light",
  },
  {
    id: "knight.cogline", name: "Cogline", importance: "supporting", function: "knight", origin: "A Convergence League route-maintenance patrol that protects moving machinery.", faction: "Convergence League", personality: ["dutiful", "literal", "quietly inventive"], traits: ["guards moving parts", "updates old mechanisms", "shares safe procedures"], strengths: ["maintenance", "reliability", "mechanical knowledge"], weaknesses: ["hesitates without a manual", "takes obsolete rules seriously"], storyUse: "Shows a knight whose role is technical protection rather than combat dominance.", firstContact: "Asks the player to wait while a machine decides which direction is forward.", recurrence: "recurring", loreWeight: "moderate",
  },
  {
    id: "knight.ice-thread", name: "Ice Thread", importance: "supporting", function: "knight", origin: "A Frost Reign marker patrol that repairs routes too thin for ordinary equipment.", faction: "Frost Reign", personality: ["calm", "brave", "quietly stubborn"], traits: ["uses fine route lines", "repairs fragile marks", "helps nervous trainees"], strengths: ["precision", "courage", "surface control"], weaknesses: ["underestimates exhaustion", "rarely asks for help"], storyUse: "Provides a grounded view of the Frost Reign’s dangerous maintenance work.", firstContact: "Offers a thin safe line and admits it is only safe if respected.", recurrence: "occasional", loreWeight: "moderate",
  },
  {
    id: "npc.morrow-mint", name: "Morrow Mint", importance: "recurring", function: "friend", origin: "A travelling refreshment cart that follows racers between ordinary and strange routes.", personality: ["friendly", "observant", "unhurried"], traits: ["remembers orders", "hears quiet news", "offers calm after dangerous races"], strengths: ["hospitality", "social memory", "emotional steadiness"], weaknesses: ["avoids bad news", "sometimes waits too long to intervene"], storyUse: "Adds a dependable emotional rest point where the player can hear small truths without an exposition dump.", firstContact: "Offers a drink and asks whether the finish line was meant to be there.", recurrence: "recurring", loreWeight: "light",
  },
  {
    id: "npc.pocket-storm", name: "Pocket Storm", importance: "background", function: "acquaintance", origin: "A tiny contained weather system carried between forecast stations.", personality: ["restless", "dramatic", "curious"], traits: ["changes pressure", "reacts to applause", "hides small lightning"], strengths: ["weather sensing", "energy", "novelty"], weaknesses: ["cannot stay quiet", "mistakes attention for danger"], storyUse: "Makes environmental science playful while providing a visual sign that weather systems can be transported.", firstContact: "Rumbles inside a container and appears pleased when the player notices.", recurrence: "occasional", loreWeight: "moderate",
  },
];
