import { CHARACTER_DATABASE_BATCH_02 } from "./characterDatabaseBatch02";
import { CHARACTER_DATABASE_BATCH_03 } from "./characterDatabaseBatch03";

export type CharacterImportance = "central" | "major" | "recurring" | "supporting" | "background";
export type CharacterFunction = "protagonist" | "guide" | "boss" | "rival" | "knight" | "friend" | "acquaintance" | "event-contact" | "world-worker";

export interface CharacterRecord {
  id: string;
  name: string;
  importance: CharacterImportance;
  function: CharacterFunction;
  origin: string;
  faction?: string;
  personality: string[];
  traits: string[];
  strengths: string[];
  weaknesses: string[];
  storyUse: string;
  firstContact: string;
  recurrence: "single" | "occasional" | "recurring" | "campaign";
  loreWeight: "light" | "moderate" | "heavy";
}

/**
 * Batch 01 is a proposed character layer. It expands the world without
 * declaring every detail permanent canon before the wider lore is supplied.
 */
export const CHARACTER_DATABASE_BATCH_01: CharacterRecord[] = [
  {
    id: "character.protagonist",
    name: "The Main Character",
    importance: "central",
    function: "protagonist",
    origin: "An ordinary racing world whose larger history is not yet known.",
    personality: ["cheerful", "laid-back", "curious", "funny", "quietly persistent"],
    traits: ["asks simple questions with large consequences", "keeps moving under pressure", "competitive without being cruel"],
    strengths: ["adaptability", "recovery", "social openness"],
    weaknesses: ["impulsive curiosity", "underestimates danger", "does not always notice personal significance"],
    storyUse: "The player's viewpoint and the person through whom the tangled chain becomes visible.",
    firstContact: "Already present at the opening race.",
    recurrence: "campaign",
    loreWeight: "heavy",
  },
  {
    id: "character.static",
    name: "Static",
    importance: "major",
    function: "guide",
    origin: "Unknown; apparently assembled, assigned, or awakened for observation and route support.",
    personality: ["analytical", "observant", "literal", "patient until ignored", "dryly funny"],
    traits: ["records anomalies", "notices performance inconsistencies", "asks precise follow-up questions"],
    strengths: ["measurement", "pattern recognition", "risk assessment"],
    weaknesses: ["takes incomplete data seriously", "struggles with jokes", "cannot explain what it has not measured"],
    storyUse: "The first character to notice that the protagonist's small extra efforts do not fit expected calculations.",
    firstContact: "A practical guide during the opening race.",
    recurrence: "campaign",
    loreWeight: "heavy",
  },
  {
    id: "boss.aether-sovereign",
    name: "Aether Sovereign",
    importance: "major",
    function: "boss",
    origin: "Sky Dominion; a high-altitude racer accustomed to unstable routes and changing winds.",
    faction: "Sky Dominion",
    personality: ["composed", "friendly when challenged", "ceremonial without being cruel"],
    traits: ["offers answers after races", "treats weather as conversation", "likes elegant routes"],
    strengths: ["control", "prediction", "environmental adaptation"],
    weaknesses: ["overcomplicates simple choices", "assumes others enjoy precision as much as he does"],
    storyUse: "A first influential racer who confirms that finish lines can behave unusually but refuses to explain everything.",
    firstContact: "A race offered as the price of a useful direction.",
    recurrence: "recurring",
    loreWeight: "heavy",
  },
  {
    id: "boss.cinder-axis",
    name: "Cinder Axis",
    importance: "major",
    function: "boss",
    origin: "Ash Banner; shaped by hot rock, unstable channels, and a culture that respects preparation.",
    faction: "Ash Banner",
    personality: ["intense", "practical", "protective", "easily impressed by competence"],
    traits: ["tests heat preparation", "notices equipment details", "speaks plainly"],
    strengths: ["heat tolerance", "durability", "route discipline"],
    weaknesses: ["poor patience for improvisation", "takes preventable mistakes personally"],
    storyUse: "Shows that a boss can be a demanding teacher and a faction representative without being a villain.",
    firstContact: "A volcanic challenge with a clear preparation requirement.",
    recurrence: "occasional",
    loreWeight: "moderate",
  },
  {
    id: "boss.glacier-sigil",
    name: "Glacier Sigil",
    importance: "major",
    function: "boss",
    origin: "Frost Reign; an old ice-route specialist who remembers paths that no longer exist.",
    faction: "Frost Reign",
    personality: ["quiet", "precise", "kind but difficult to read"],
    traits: ["speaks in route metaphors", "keeps old maps", "waits before answering"],
    strengths: ["surface control", "patience", "memory"],
    weaknesses: ["slow to trust new explanations", "can mistake caution for certainty"],
    storyUse: "Connects environmental history to the question of whether tracks remember previous racers.",
    firstContact: "A frozen route requiring control rather than speed alone.",
    recurrence: "occasional",
    loreWeight: "heavy",
  },
  {
    id: "boss.rift-echelon",
    name: "Rift Echelon",
    importance: "major",
    function: "boss",
    origin: "Null Veil; a racer associated with routes that are difficult to classify or repeat.",
    faction: "Null Veil",
    personality: ["clever", "sly", "playfully evasive"],
    traits: ["answers questions with tests", "remembers embarrassing details", "enjoys uncertainty"],
    strengths: ["risk reading", "misdirection", "fast adaptation"],
    weaknesses: ["creates confusion for entertainment", "sometimes believes their own tricks"],
    storyUse: "Introduces contradictory explanations without forcing the story to choose one immediately.",
    firstContact: "A challenge where the obvious route is not necessarily the useful route.",
    recurrence: "recurring",
    loreWeight: "heavy",
  },
  {
    id: "boss.circuit-steward",
    name: "The Circuit Steward",
    importance: "major",
    function: "boss",
    origin: "Convergence League; responsible for coordinating racers who arrive from incompatible routes.",
    faction: "Convergence League",
    personality: ["organized", "welcoming", "overworked", "proud of bad signage"],
    traits: ["values team coordination", "knows many names", "keeps incomplete schedules"],
    strengths: ["coordination", "networking", "logistics"],
    weaknesses: ["loses track of causality", "treats obvious system failures as temporary"],
    storyUse: "A bridge between team competition, dimensional traffic, and the old unfinished systems.",
    firstContact: "A team challenge that requires cooperation rather than one perfect racer.",
    recurrence: "recurring",
    loreWeight: "heavy",
  },
  {
    id: "rival.basil-varn",
    name: "Basil Varn",
    importance: "major",
    function: "rival",
    origin: "Amber Circuit; a route-focused racer who believes consistency beats spectacle.",
    faction: "Amber Circuit",
    personality: ["competitive", "tactical", "polite until losing"],
    traits: ["studies opponents", "keeps score honestly", "returns after setbacks"],
    strengths: ["planning", "surface reading", "reliability"],
    weaknesses: ["overthinks improvisation", "hates losing to accidents"],
    storyUse: "A recurring rival who can become an ally, a stronger competitor, or eventually an influential racer in his own right.",
    firstContact: "A fair race followed by an argument about whether the finish line moved.",
    recurrence: "recurring",
    loreWeight: "moderate",
  },
  {
    id: "rival.cinder-vale",
    name: "Cinder Vale",
    importance: "major",
    function: "rival",
    origin: "Crimson Zero; a fast racer who treats risk as a form of self-expression.",
    faction: "Crimson Zero",
    personality: ["bold", "impatient", "charismatic", "secretly thoughtful"],
    traits: ["takes shortcuts", "learns after failure", "collects stories from dangerous tracks"],
    strengths: ["speed", "bravery", "momentum management"],
    weaknesses: ["poor restraint", "confuses confidence with preparation"],
    storyUse: "Demonstrates how a rival can develop independently and carry information without being a lore narrator.",
    firstContact: "An aggressive challenge where the fastest route is not the safest route.",
    recurrence: "recurring",
    loreWeight: "moderate",
  },
  {
    id: "npc.sly-mark",
    name: "Sly-Mark",
    importance: "recurring",
    function: "acquaintance",
    origin: "A collection of temporary tracks and unofficial shortcuts.",
    personality: ["smooth", "helpful when profitable", "dramatic about ordinary information"],
    traits: ["knows who is arriving", "sells directions", "never admits to guessing"],
    strengths: ["social awareness", "timing", "finding routes"],
    weaknesses: ["reliability depends on mood", "embellishes simple facts"],
    storyUse: "A small recurring contact who can notify the player of events without carrying the main plot.",
    firstContact: "Appears beside a sign that clearly does not belong to him.",
    recurrence: "recurring",
    loreWeight: "light",
  },
  {
    id: "npc.mosswheel",
    name: "Mosswheel",
    importance: "supporting",
    function: "world-worker",
    origin: "A living track region where vegetation responds to vibration.",
    personality: ["patient", "quietly humorous", "protective of small creatures"],
    traits: ["repairs living surfaces", "recognizes footsteps", "dislikes unnecessary noise"],
    strengths: ["environmental knowledge", "care", "observation"],
    weaknesses: ["slow to react to urgent changes", "assumes everyone notices subtle movement"],
    storyUse: "Introduces biology through practical track maintenance rather than exposition.",
    firstContact: "Requests that the player stop rolling over a sleeping patch of terrain.",
    recurrence: "occasional",
    loreWeight: "moderate",
  },
  {
    id: "npc.pip-salvage",
    name: "Pip Salvage",
    importance: "supporting",
    function: "friend",
    origin: "A scrapyard between commonly used finish-line routes.",
    personality: ["enthusiastic", "inventive", "easily distracted"],
    traits: ["repurposes broken equipment", "names every tool", "finds useful objects by accident"],
    strengths: ["crafting", "improvisation", "resourcefulness"],
    weaknesses: ["keeps unsafe prototypes", "forgets where important parts came from"],
    storyUse: "Supports upgrades and may accidentally uncover creator-era components.",
    firstContact: "Offers a grip modification after mistaking the protagonist for a delivery.",
    recurrence: "recurring",
    loreWeight: "moderate",
  },
  {
    id: "npc.brassettle",
    name: "Brassettle",
    importance: "supporting",
    function: "world-worker",
    origin: "Old maintenance corridors beneath the first connected tracks.",
    personality: ["fussy", "proud", "easily offended by incorrect labels"],
    traits: ["paints signs", "maintains route markers", "knows which repairs were never finished"],
    strengths: ["memory", "organization", "technical craft"],
    weaknesses: ["cannot explain symbols simply", "refuses to remove obsolete signs"],
    storyUse: "Connects comedy and ordinary maintenance work to the larger creator mystery.",
    firstContact: "Insists that a sign saying 'temporary' has been temporary for a very long time.",
    recurrence: "occasional",
    loreWeight: "moderate",
  },
  {
    id: "npc.nix-weather",
    name: "Nix Weather",
    importance: "recurring",
    function: "event-contact",
    origin: "A high pass where wind patterns change faster than official forecasts.",
    personality: ["alert", "chatty", "dramatic about measurements"],
    traits: ["announces environmental changes", "collects failed predictions", "likes visible data"],
    strengths: ["forecasting", "communication", "rapid observation"],
    weaknesses: ["overstates danger", "updates forecasts too often"],
    storyUse: "Notifies the player of environmental events while keeping scientific information approachable.",
    firstContact: "Warns the player about wind, then immediately admits the wind was not predicted.",
    recurrence: "recurring",
    loreWeight: "light",
  },
  {
    id: "npc.loop-clerk",
    name: "Loop",
    importance: "supporting",
    function: "event-contact",
    origin: "A checkpoint station that appears in more places than its map allows.",
    personality: ["professional", "calm", "quietly confused"],
    traits: ["checks entries", "remembers previous attempts", "never comments on the station moving"],
    strengths: ["routine", "record keeping", "fairness"],
    weaknesses: ["trusts forms more than observations", "cannot decide which station is the original"],
    storyUse: "Delivers challenge requirements and hints that locations may not be as fixed as they appear.",
    firstContact: "Requests a checkpoint stamp from a race that has not started yet.",
    recurrence: "recurring",
    loreWeight: "moderate",
  },
  {
    id: "npc.mallow",
    name: "Mallow",
    importance: "background",
    function: "acquaintance",
    origin: "A rest stop between volcanic and ordinary terrain.",
    personality: ["warm", "observant", "unimpressed by famous racers"],
    traits: ["serves heat-safe snacks", "remembers preferences", "hears rumors without chasing them"],
    strengths: ["hospitality", "social memory", "emotional steadiness"],
    weaknesses: ["avoids direct confrontation", "occasionally repeats a rumor incorrectly"],
    storyUse: "Makes the world feel inhabited and can deliver small clues through ordinary conversation.",
    firstContact: "Offers the protagonist something cool and asks whether the track was supposed to do that.",
    recurrence: "occasional",
    loreWeight: "light",
  },
  {
    id: "npc.quarry-repair",
    name: "Quarry",
    importance: "supporting",
    function: "world-worker",
    origin: "A rocky route repeatedly damaged by ambitious racers.",
    personality: ["direct", "practical", "secretly sentimental about tracks"],
    traits: ["repairs collision zones", "tests materials by sound", "knows which obstacles are intentional"],
    strengths: ["construction", "material knowledge", "patience"],
    weaknesses: ["does not understand dimensional markings", "refuses to call a repair finished until it is overbuilt"],
    storyUse: "Connects material science and track history without turning either into a lecture.",
    firstContact: "Asks the player to report whether a boulder moved or the track moved around it.",
    recurrence: "occasional",
    loreWeight: "moderate",
  },
  {
    id: "npc.vela-cartographer",
    name: "Vela",
    importance: "recurring",
    function: "friend",
    origin: "A map room assembled from route fragments gathered after dimensional transitions.",
    personality: ["focused", "curious", "patient with questions but not with bad maps"],
    traits: ["compares route patterns", "marks contradictions", "keeps maps with missing centers"],
    strengths: ["cartography", "analysis", "long-term memory"],
    weaknesses: ["follows patterns too eagerly", "has difficulty accepting a map may be wrong"],
    storyUse: "Turns the finish-line mystery into a gradual pattern of locations rather than an immediate revelation.",
    firstContact: "Recognizes a symbol from the protagonist's route but cannot place where she first saw it.",
    recurrence: "recurring",
    loreWeight: "heavy",
  },
  {
    id: "npc.drift-apprentice",
    name: "Drift",
    importance: "recurring",
    function: "acquaintance",
    origin: "A beginner circuit that shares training routes with the protagonist's early races.",
    personality: ["eager", "honest", "easily impressed", "occasionally competitive"],
    traits: ["copies techniques", "asks direct questions", "returns with small improvements"],
    strengths: ["learning", "enthusiasm", "persistence"],
    weaknesses: ["takes advice too literally", "attempts advanced maneuvers too early"],
    storyUse: "Shows how the protagonist's reputation begins affecting ordinary racers.",
    firstContact: "Asks how the protagonist stayed moving after a failed turn.",
    recurrence: "recurring",
    loreWeight: "light",
  },
  {
    id: "npc.rook-rumor",
    name: "Rook",
    importance: "supporting",
    function: "event-contact",
    origin: "A crowded exchange route where rumors move faster than racers.",
    personality: ["confident", "sociable", "wrong often enough to be useful"],
    traits: ["collects stories", "connects unrelated details", "occasionally reports a true thing for the wrong reason"],
    strengths: ["networking", "recall", "creative interpretation"],
    weaknesses: ["cannot separate rumor from evidence", "gets bored by verification"],
    storyUse: "Provides contradictory clues and lets the player decide what deserves investigation.",
    firstContact: "Claims to know why finish lines move, then admits he was talking about a different finish line.",
    recurrence: "recurring",
    loreWeight: "moderate",
  },
];

export const getCharacterById = (id: string): CharacterRecord | undefined =>
  CHARACTER_DATABASE_ALL.find((character) => character.id === id);

export const getCharactersByFunction = (characterFunction: CharacterFunction): CharacterRecord[] =>
  CHARACTER_DATABASE_ALL.filter((character) => character.function === characterFunction);

export const CHARACTER_DATABASE_ALL: CharacterRecord[] = [
  ...CHARACTER_DATABASE_BATCH_01,
  ...CHARACTER_DATABASE_BATCH_02,
  ...CHARACTER_DATABASE_BATCH_03,
];
