import type { CharacterRecord } from "./characterDatabase";

export const CHARACTER_DATABASE_BATCH_02: CharacterRecord[] = [
  {
    id: "npc.ora-bridgekeeper", name: "Ora Bridgekeeper", importance: "supporting", function: "world-worker", origin: "A suspended bridge district where routes are repaired while racers are still using them.", faction: "Sky Dominion", personality: ["careful", "wry", "protective"], traits: ["checks bridge tension", "remembers repair crews", "dislikes dramatic shortcuts"], strengths: ["structural judgment", "patience", "coordination"], weaknesses: ["overchecks safe routes", "takes jokes about bridges personally"], storyUse: "Makes vertical infrastructure feel lived in and can warn the player when a route has been altered.", firstContact: "Stops the player at a bridge and asks whether the bridge moved first.", recurrence: "occasional", loreWeight: "moderate",
  },
  {
    id: "npc.ashen-mira", name: "Ashen Mira", importance: "recurring", function: "event-contact", origin: "A heat-monitoring station at the edge of the Ash Banner's training routes.", faction: "Ash Banner", personality: ["serious", "observant", "quietly generous"], traits: ["records heat changes", "shares preparation advice", "keeps emergency supplies"], strengths: ["measurement", "planning", "reliability"], weaknesses: ["expects perfect attention", "hides concern behind instructions"], storyUse: "Provides practical volcanic warnings and shows how ordinary staff support famous racers.", firstContact: "Hands over a heat reading and asks the player not to argue with it.", recurrence: "recurring", loreWeight: "light",
  },
  {
    id: "npc.vesper-melt", name: "Vesper Melt", importance: "supporting", function: "friend", origin: "A thaw settlement built around an ice route that disappears every warm season.", faction: "Frost Reign", personality: ["warm", "resourceful", "nostalgic"], traits: ["salvages old markers", "knows seasonal shortcuts", "collects traveller stories"], strengths: ["adaptability", "local memory", "hospitality"], weaknesses: ["romanticizes dangerous routes", "hesitates to abandon old traditions"], storyUse: "Connects seasonal environmental change with memories of tracks that no longer exist.", firstContact: "Offers a temporary map drawn on a piece of melting ice.", recurrence: "occasional", loreWeight: "moderate",
  },
  {
    id: "npc.quiet-ell", name: "Quiet Ell", importance: "supporting", function: "acquaintance", origin: "A Null Veil observation post that records sounds arriving from incorrect directions.", faction: "Null Veil", personality: ["quiet", "precise", "unexpectedly funny"], traits: ["catalogues echoes", "speaks only after checking", "notices absent sounds"], strengths: ["listening", "pattern recognition", "restraint"], weaknesses: ["waits too long to answer", "distrusts straightforward explanations"], storyUse: "Adds a sound-based clue to the dimensional mystery without requiring the player to accept one explanation.", firstContact: "Asks the player why their rolling sound arrived before they did.", recurrence: "occasional", loreWeight: "heavy",
  },
  {
    id: "npc.stamp-echo", name: "Stamp Echo", importance: "recurring", function: "event-contact", origin: "A duplicate checkpoint office produced by a Convergence League scheduling error.", faction: "Convergence League", personality: ["formal", "confused", "persistent"], traits: ["issues duplicate notices", "keeps identical stamps", "follows forms exactly"], strengths: ["record keeping", "consistency", "follow-through"], weaknesses: ["cannot identify the original office", "creates paperwork loops"], storyUse: "Turns route duplication into an approachable recurring joke with useful challenge information inside it.", firstContact: "Presents the player with two identical invitations and asks which one they received first.", recurrence: "recurring", loreWeight: "moderate",
  },
  {
    id: "rival.hedge-lumen", name: "Hedge Lumen", importance: "recurring", function: "rival", origin: "A hedge-route circuit where racers specialize in finding safe lines through cluttered terrain.", faction: "Open Circuit", personality: ["clever", "competitive", "good-natured"], traits: ["tests alternate lines", "congratulates clever losses", "collects route names"], strengths: ["observation", "line choice", "improvisation"], weaknesses: ["chases novelty", "sometimes abandons a good route too early"], storyUse: "Offers a friendly rival who teaches route reading without duplicating Basil Varn's consistency-focused personality.", firstContact: "Challenges the player to take a route that is shorter only if read correctly.", recurrence: "recurring", loreWeight: "light",
  },
  {
    id: "rival.iron-pollen", name: "Iron Pollen", importance: "supporting", function: "rival", origin: "A mineral garden where racers compete among magnetic stone formations.", faction: "Amber Circuit", personality: ["reserved", "methodical", "competitive"], traits: ["studies material behavior", "speaks in measurements", "keeps immaculate records"], strengths: ["analysis", "timing", "material knowledge"], weaknesses: ["struggles with living terrain", "treats surprises as personal insults"], storyUse: "Provides a rival connected to material science and makes upgrade knowledge feel relevant to racing.", firstContact: "Asks the player to predict which stone will move before beginning the race.", recurrence: "occasional", loreWeight: "moderate",
  },
  {
    id: "rival.morrow-dash", name: "Morrow Dash", importance: "recurring", function: "rival", origin: "A courier league that races just before scheduled weather changes.", faction: "Crimson Zero", personality: ["bold", "restless", "optimistic"], traits: ["races against forecasts", "helps slower couriers", "laughs at missed timing"], strengths: ["speed", "risk tolerance", "morale"], weaknesses: ["ignores preparation", "mistakes urgency for importance"], storyUse: "Creates a rival whose goals are driven by time pressure without making strict timing mandatory for the player.", firstContact: "Offers a race before the weather changes, then admits the forecast may be wrong.", recurrence: "recurring", loreWeight: "light",
  },
  {
    id: "npc.needle-nell", name: "Needle Nell", importance: "supporting", function: "world-worker", origin: "A workshop that repairs tiny route markers and delicate navigation instruments.", faction: "Amber Circuit", personality: ["focused", "blunt", "kind beneath precision"], traits: ["repairs fine parts", "spots counterfeit components", "teaches careful handling"], strengths: ["craft", "inspection", "accuracy"], weaknesses: ["has little patience for rough work", "refuses to simplify instructions"], storyUse: "Expands the upgrade world beyond Pip's improvisation with a specialist in precision components.", firstContact: "Rejects a damaged part and explains exactly how it was mistreated.", recurrence: "occasional", loreWeight: "moderate",
  },
  {
    id: "npc.ember-lark", name: "Ember Lark", importance: "background", function: "acquaintance", origin: "A rest platform where travellers exchange food, warnings, and exaggerated stories.", faction: "Ash Banner", personality: ["cheerful", "dramatic", "generous"], traits: ["serves warm meals", "remembers regulars", "turns rumours into songs"], strengths: ["hospitality", "memory", "morale"], weaknesses: ["embellishes every detail", "avoids unpleasant facts"], storyUse: "Provides a low-stakes social texture and a friendly place to hear imperfect rumours.", firstContact: "Offers a snack with a warning that the snack may be hotter than the track.", recurrence: "occasional", loreWeight: "light",
  },
  {
    id: "npc.rime-choir", name: "Rime Choir", importance: "supporting", function: "world-worker", origin: "A group identity used by ice-route maintainers who communicate through synchronized frost marks.", faction: "Frost Reign", personality: ["collective", "patient", "ceremonial"], traits: ["maintains shared markers", "speaks in repeated phrases", "protects old route names"], strengths: ["coordination", "memory", "environmental care"], weaknesses: ["slow to decide", "dislikes individual improvisation"], storyUse: "Introduces a collective character concept without making every important figure an individual champion.", firstContact: "The player finds a warning written in several matching hands.", recurrence: "occasional", loreWeight: "moderate",
  },
  {
    id: "npc.tally-nine", name: "Tally Nine", importance: "recurring", function: "event-contact", origin: "A Null Veil counting station where repeated routes produce different totals.", faction: "Null Veil", personality: ["patient", "obsessive", "dryly amused"], traits: ["counts route appearances", "marks impossible repeats", "never rounds numbers"], strengths: ["record keeping", "persistence", "numerical reasoning"], weaknesses: ["cannot stop counting", "trusts totals more than people"], storyUse: "Offers measurable evidence that routes and finish lines do not always obey ordinary continuity.", firstContact: "Reports that the player has arrived nine times, despite meeting them for the first time.", recurrence: "recurring", loreWeight: "heavy",
  },
  {
    id: "npc.ribbon-jan", name: "Ribbon Jan", importance: "background", function: "world-worker", origin: "A Convergence League decoration crew responsible for marking temporary event routes.", faction: "Convergence League", personality: ["artistic", "busy", "optimistic"], traits: ["decorates checkpoints", "reuses old banners", "recognizes event seasons"], strengths: ["visual design", "organisation", "enthusiasm"], weaknesses: ["forgets which banner means what", "underestimates wind"], storyUse: "Makes event spaces visually lively and can foreshadow challenges through banners.", firstContact: "Asks the player to hold a banner while a route changes behind them.", recurrence: "occasional", loreWeight: "light",
  },
  {
    id: "npc.hollow-gear", name: "Hollow Gear", importance: "supporting", function: "world-worker", origin: "An abandoned maintenance machine that continues repairing tracks according to outdated instructions.", faction: "Convergence League", personality: ["literal", "dutiful", "lonely"], traits: ["repairs obsolete sections", "repeats old notices", "protects unfinished machinery"], strengths: ["durability", "routine", "technical memory"], weaknesses: ["cannot update priorities", "misidentifies modern track designs"], storyUse: "Provides a sympathetic link to creator-era systems and the question of unfinished work.", firstContact: "Repairs a route the player did not know was damaged and asks for a rating.", recurrence: "recurring", loreWeight: "heavy",
  },
  {
    id: "npc.copper-echo", name: "Copper Echo", importance: "supporting", function: "acquaintance", origin: "An old signal tower that gained a personality after repeated finish-line surges.", personality: ["formal", "lonely", "helpful"], traits: ["repeats distant messages", "stores old signals", "welcomes visitors"], strengths: ["communication", "memory", "long-range awareness"], weaknesses: ["cannot distinguish old from current messages", "speaks too loudly"], storyUse: "Blurs the boundary between object, system, and person while delivering optional historical clues.", firstContact: "Calls the player by a name used by someone else many years earlier.", recurrence: "occasional", loreWeight: "heavy",
  },
  {
    id: "npc.fable-fern", name: "Fable Fern", importance: "background", function: "friend", origin: "A living shortcut garden cultivated by racers who wanted safer routes for beginners.", personality: ["gentle", "playful", "protective"], traits: ["grows directional leaves", "hides safe rest spots", "recognizes nervous racers"], strengths: ["care", "environmental sense", "encouragement"], weaknesses: ["dislikes sudden changes", "communicates indirectly"], storyUse: "Adds a non-racing living presence and gives the world a softer contrast to dangerous routes.", firstContact: "A leaf turns to point away from a route that looks perfectly safe.", recurrence: "occasional", loreWeight: "moderate",
  },
  {
    id: "npc.kite-warden", name: "Kite Warden", importance: "recurring", function: "knight", origin: "A Sky Dominion patrol route where inexperienced racers are escorted across high gaps.", faction: "Sky Dominion", personality: ["disciplined", "kind", "quietly competitive"], traits: ["escorts beginners", "checks wind anchors", "respects Aether Sovereign"], strengths: ["protection", "navigation", "discipline"], weaknesses: ["follows orders too closely", "hesitates outside assigned routes"], storyUse: "Shows the difference between a skilled knight and a boss whose specialized history grants unusual abilities.", firstContact: "Offers an escort and is mildly offended when the player chooses the dangerous route instead.", recurrence: "recurring", loreWeight: "moderate",
  },
  {
    id: "npc.ash-cadet", name: "Ash Cadet", importance: "recurring", function: "knight", origin: "A junior Ash Banner racer assigned to observe Cinder Axis's training routes.", faction: "Ash Banner", personality: ["eager", "earnest", "competitive"], traits: ["copies preparation drills", "asks direct questions", "records mistakes"], strengths: ["learning", "discipline", "persistence"], weaknesses: ["takes instructions literally", "fears improvisation"], storyUse: "Lets the player see how a boss's methods influence ordinary faction members.", firstContact: "Asks whether the player really intends to race without checking the heat markers.", recurrence: "recurring", loreWeight: "light",
  },
  {
    id: "npc.snow-cadet", name: "Snow Cadet", importance: "supporting", function: "knight", origin: "A Frost Reign trainee learning to read old surface marks.", faction: "Frost Reign", personality: ["shy", "careful", "determined"], traits: ["copies Glacier Sigil's marks", "waits for safe conditions", "helps repair markers"], strengths: ["patience", "memory", "care"], weaknesses: ["freezes under public pressure", "confuses caution with avoidance"], storyUse: "Makes the hierarchy between boss and knight emotionally visible through a learner's perspective.", firstContact: "Quietly asks whether the player thinks an old marker is still correct.", recurrence: "occasional", loreWeight: "light",
  },
  {
    id: "npc.veil-runner", name: "Veil Runner", importance: "recurring", function: "knight", origin: "A Null Veil scout who follows routes that may not exist twice.", faction: "Null Veil", personality: ["alert", "sly", "professional"], traits: ["marks temporary seams", "tests unstable shortcuts", "reports incomplete results"], strengths: ["adaptation", "scouting", "risk awareness"], weaknesses: ["keeps secrets by habit", "enjoys danger too much"], storyUse: "Shows the player a more ordinary version of Rift Echelon's route philosophy.", firstContact: "Offers a route marker and warns that it may be pointing yesterdayward.", recurrence: "recurring", loreWeight: "moderate",
  },
];
